---
title: "Code in AEA Articles"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(EconJournalData)
setwd("D:/libraries/EconJournalData/")
db = get.articles.db()

sql = 
"SELECT f.*, a.year, a.journ 
FROM files_summary f, article a
WHERE f.id = a.id"

dat = dbGet(db,sql=sql, schema=NULL)
```

## Development of Script Types Over Years

```{r cars}
library(dplyr)
ds = filter(dat, is_code==1) %>%
  mutate_rows(file_type=="ado", file_type="do") %>%
  group_by(year, file_type) %>%
  summarize(n_yf = n()) %>%
  group_by(year) %>%
  mutate(n_y = sum(n_yf), share = n_yf / n_y) %>%
  ungroup() %>%
  arrange(year,-share)
ds  


d = filter(ds, file_type %in% c("r","py","jl","do","m"))

library(ggplot2)
ggplot(d, aes(x=year, y=share, color=file_type)) + geom_line(size=1.5) + scale_y_log10() + theme_bw()


d = filter(ds, file_type %in% c("r","py","jl"))
ggplot(d, aes(x=year, y=share, color=file_type)) + geom_line(size=1.5) + scale_y_log10() + theme_bw()

```




```{r cars}
library(dplyr)
ds = filter(dat, is_code==1) %>%
  mutate_rows(file_type=="ado", file_type="do") %>%
  group_by(year, journ, file_type) %>%
  summarize(n_yf = n()) %>%
  group_by(year, journ) %>%
  mutate(n_y = sum(n_yf), share = n_yf / n_y) %>%
  ungroup() %>%
  arrange(year,-share)
ds

d = filter(ds, file_type %in% c("r","py","jl"))
ggplot(d, aes(x=year, y=share, color=file_type)) + geom_line(size=1.5) + scale_y_log10() + theme_bw() + facet_wrap(~journ)


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
